
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parserpack;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 6;
  public static final int DOCE = 4;
  public static final int INTEIRO = 2;
  public static final int MENOS = 7;
  public static final int MULT = 8;
  public static final int LETRA = 3;
  public static final int EOF = 0;
  public static final int DIV = 9;
  public static final int error = 1;
  public static final int INVALIDO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEIRO",
  "LETRA",
  "DOCE",
  "INVALIDO",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV"
  };
}

